version: '3.9'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
    - '6831:6831/udp'
    - '6832:6832/udp'
    - '4317:4317'
    - '4318:4318'
    - '16686:16686'
    - '14268:14268'

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: metastable
      POSTGRES_PASSWORD: J4dyW6943mAsfMJNausxNsnB8jcneMej
      POSTGRES_DB: metastable_development
    ports:
    - 5432:5432
