on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up buildpack
      uses: buildpacks/github-actions/setup-pack@v4.8.0
    - name: Build image
      run: |
        pack build ghcr.io/rwx-im/meta-dream:latest \
          --buildpack paketo-buildpacks/python \
          --cache-image ghcr.io/rwx-im/meta-dream:cache \
          --publish
